### ISSUE TITLE
Move CovidQA experiments into separate page

### ISSUE THREAD

**Issue by lintool** [castorini/pygaggle#31]
Instead of directly at top-level README, move into a separate page, like https://github.com/castorini/pygaggle/blob/master/docs/experiments-msmarco-passage.md so we can also start a replication log.

@ronakice @daemon thoughts?

**Comment by ronakice** [comment]
Agreed! I was looking at how to best do this as you posted this! Since pygaggle is a ranker for multiple datasets this would be ideal. Should we separate out unsupervised techniques from supervised? Else there will be a lot of replication to do. I can take this on if you want and get the two URAs to verify.

**Comment by ronakice** [comment]
Also do we go with replication on version 0.2 or 0.1?

**Comment by lintool** [comment]
version 0.2; version 0.1 is defunct.

we probably want to put the version 0.2 numbers directly on the md page, since the arxiv paper is always going to lag behind...

**Comment by ronakice** [comment]
Sounds good once we hear from Raphael I'll go ahead with it!

**Comment by lintool** [comment]
@ronakice I think we should go ahead and do this? I'm assuming @daemon just missed this note above.

**Comment by ronakice** [comment]
Yep, I'll go ahead with it.
