### ISSUE TITLE
Flatten the structure of the ground truth JSON

### ISSUE THREAD

**Issue by lintool** [castorini/pygaggle#8]
For v0.0.2 of the dataset, should we flatten the nested hierarchy?

Currently, we have subcategories nested within categories. I propose to undo the nesting and just have something like:

```
[{
   category: ...
   subcategory: ...
}, {

}
...]
```

That way, when we start integrating other sources, we wouldn't need to jam things into this rigid structure.

Thoughts?

**Comment by daemon** [comment]
We could have a `raw/` folder of all the "raw" datasets containing the source-specific structure, from which a main dataset.json is coalesced.

**Comment by lintool** [comment]
I think this is independent of a flat vs. a nested structure, because I can imagine answers from elsewhere that don't fit into a category/subcategory hierarchy.

But FWIW, I think `raw/` is over-engineering at this point... I would still vote for a single file.

**Comment by daemon** [comment]
The way it's organized on Kaggle definitely fits better into a nested structure, so that could be `raw/kaggle.json`. Other sources might not have a category/subcategory hierarchy and thus would be flat.

But I'm okay with a flat file if we discard category/subcategory names, which would be redundant across many examples.

**Comment by lintool** [comment]
Okay, let's keep the structure for now then.
